
spring:
  application:
    name: banking-gateway

  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account-service/**
          filters:
            - StripPrefix=1
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer-service/**
          filters:
            - StripPrefix=1
        - id: movement-service
          uri: lb://movement-service
          predicates:
            - Path=/movement-service/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    status-page-url-path: /swagger-ui/

resilience4j:
  circuitbreaker:
    configs:
      defecto:
        slidingWindowSize: 6
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 4
        slowCallRateThreshold: 2
      instances:
        products:
          base-config: defecto
  timelimiter:
    configs:
      defecto:
        timeoutDuration: 2s
      instances:
        products:
          base-config: defecto

server:
  port: 8090